<?php 
date_default_timezone_set("Asia/Calcutta");
error_reporting(0);
    $time = date("H:i:s");
    $date = date("d-m-Y");
    $d = explode(":", $time);
    $h = $d[0];
    $m = $d[1];
    $t = $d[2];
    if($h == '00' && $m == '00' && ($t == '00' || $t == '01')){
    	$fp = fopen("log.php", 'a');
    		
        fwrite($fp,'<center><hr>'.$date.'</hr></center>');
        
        fclose($fp);
    }
  
 ?>

            <br><div class='msgln' style='background-color:#fff;height:auto;min-height:120px;color:#000;box-shadow: 5px 5px 3px #888888;overflow:auto;'> <img src='https://media.licdn.com/mpr/mprx/0_0eo-q-dnP-ouX37azJttx-_nK_zxGhlmrJtyAbmn-BoOGrGCzeYp0hfnvboxFP11PJ-prvh90qHYTX81KRfap63VsqH0TXQ7zRfAcFqclzjPw-g1MEMxBPV6VT-fHXAYyZwOKzHs74u' style='border-radius:25px;height:50px;width:50px;margin-top:1.5%;margin-left:-53%;'>&nbsp;&nbsp;&nbsp;<h5 style='color:#000;display:inline;margin-top:-5%;'>Aman Bharadwaj</h5>
            <p style='margin-top:-4%;margin-left:-45%;font-size:14px;color:#757575;'><b>Dehra Dun Area, India</b></p><p style='margin-left:-76%;margin-top:4%;'><div style='width:90%;'><b>(12:14 PM)</b>:<p style='word-break: break-all;'>
                India is a vast South Asian country with diverse terrain – from Himalayan peaks to Indian Ocean coastline – and history reaching back 5 millennia. In the north, Mughal Empire landmarks include Delhi’s Red Fort complex and massive Jama Masjid mosque, plus Agra’s iconic Taj Mahal mausoleum. Pilgrims bathe in the Ganges in Varanasi, and Rishikesh is a yoga centre and base for Himalayan trekking.
           </div></p></p></div><br><div class='msgln' style='background-color:#fff;height:auto;min-height:120px;color:#000;box-shadow: 5px 5px 3px #888888;overflow:auto;'> <img src='https://media.licdn.com/mpr/mprx/0_0eo-q-dnP-ouX37azJttx-_nK_zxGhlmrJtyAbmn-BoOGrGCzeYp0hfnvboxFP11PJ-prvh90qHYTX81KRfap63VsqH0TXQ7zRfAcFqclzjPw-g1MEMxBPV6VT-fHXAYyZwOKzHs74u' style='border-radius:25px;height:50px;width:50px;margin-top:1.5%;margin-left:-53%;'>&nbsp;&nbsp;&nbsp;<h5 style='color:#000;display:inline;margin-top:-5%;'>Aman Bharadwaj</h5>
            <p style='margin-top:-4%;margin-left:-45%;font-size:14px;color:#757575;'><b>Dehra Dun Area, India</b></p><p style='margin-left:-76%;margin-top:4%;'><div style='width:80%;'><b>(12:18 PM):</b><p style='word-break: break-all;'>sdcsdc
</div></p></p></div><br><div class='msgln' style='background-color:#fff;height:auto;min-height:120px;color:#000;box-shadow: 5px 5px 3px #888888;overflow:auto;'> <img src='https://media.licdn.com/mpr/mprx/0_0eo-q-dnP-ouX37azJttx-_nK_zxGhlmrJtyAbmn-BoOGrGCzeYp0hfnvboxFP11PJ-prvh90qHYTX81KRfap63VsqH0TXQ7zRfAcFqclzjPw-g1MEMxBPV6VT-fHXAYyZwOKzHs74u' style='border-radius:25px;height:50px;width:50px;margin-top:1.5%;margin-left:-53%;'>&nbsp;&nbsp;&nbsp;<h5 style='color:#000;display:inline;margin-top:-5%;'>Aman Bharadwaj</h5>
            <p style='margin-top:-4%;margin-left:-45%;font-size:14px;color:#757575;'><b>Dehra Dun Area, India</b></p><p style='margin-left:-76%;margin-top:4%;'><div style='width:80%;'><b>(12:19 PM):</b><p style='word-break: break-all;'>sdcsdc
ed we fyguy fg ugf ug fugf yg yfg </div></p></p></div><br><div class='msgln' style='background-color:#fff;height:auto;min-height:120px;color:#000;box-shadow: 5px 5px 3px #888888;overflow:auto;'> <img src='https://media.licdn.com/mpr/mprx/0_0eo-q-dnP-ouX37azJttx-_nK_zxGhlmrJtyAbmn-BoOGrGCzeYp0hfnvboxFP11PJ-prvh90qHYTX81KRfap63VsqH0TXQ7zRfAcFqclzjPw-g1MEMxBPV6VT-fHXAYyZwOKzHs74u' style='border-radius:25px;height:50px;width:50px;margin-top:1.5%;margin-left:-53%;'>&nbsp;&nbsp;&nbsp;<h5 style='color:#000;display:inline;margin-top:-5%;'>Aman Bharadwaj</h5>
            <p style='margin-top:-4%;margin-left:-45%;font-size:14px;color:#757575;'><b>Dehra Dun Area, India</b></p><p style='margin-left:-76%;margin-top:4%;'><div style='width:80%;'><b>(1:08 AM):</b><p style='word-break: break-all;'>The U.S. is a country of 50 states covering a vast swath of North America, with Alaska in the northwest and Hawaii extending the nation’s presence into the Pacific Ocean. Major Atlantic Coast cities are New York, a global finance and culture center, and capital Washington, DC. Midwestern metropolis Chicago is known for influential architecture and on the west coast, Los Angeles' Hollywood is famed for filmmaking.
</div></p></p></div><br><div class='msgln' style='background-color:#fff;height:auto;min-height:120px;color:#000;box-shadow: 5px 5px 3px #888888;overflow:auto;'> <img src='https://media.licdn.com/mpr/mprx/0_tmY0ctNEzBlTacrivuoAJLSwrqLhmXTi4mH0-QCwAhVTmqKttEQYx8Jw9BNTIzr7NZHAnz9Iprw3DhROZjUi0QcFMrw8DhqaZjUpqbGotAY2F9ftquDtN12RJ5lKkh_0AY01Pv_i5VE' style='border-radius:25px;height:50px;width:50px;margin-top:1.5%;margin-left:-53%;'>&nbsp;&nbsp;&nbsp;<h5 style='color:#000;display:inline;margin-top:-5%;'>Devendra Sharma</h5>
            <p style='margin-top:-4%;margin-left:-45%;font-size:14px;color:#757575;'><b>Dehra Dun Area, India</b></p><p style='margin-left:-76%;margin-top:4%;'><div style='width:80%;'><b>(3:40 PM):</b><p style='word-break: break-all;'>What's the plan for today!!</div></p></p></div><br><div class='msgln' style='background-color:#fff;height:auto;min-height:120px;color:#000;box-shadow: 5px 5px 3px #888888;overflow:auto;'> <img src='https://media.licdn.com/mpr/mprx/0_tmY0ctNEzBlTacrivuoAJLSwrqLhmXTi4mH0-QCwAhVTmqKttEQYx8Jw9BNTIzr7NZHAnz9Iprw3DhROZjUi0QcFMrw8DhqaZjUpqbGotAY2F9ftquDtN12RJ5lKkh_0AY01Pv_i5VE' style='border-radius:25px;height:50px;width:50px;margin-top:1.5%;margin-left:-53%;'>&nbsp;&nbsp;&nbsp;<h5 style='color:#000;display:inline;margin-top:-5%;'>Devendra Sharma</h5>
            <p style='margin-top:-4%;margin-left:-45%;font-size:14px;color:#757575;'><b>Dehra Dun Area, India</b></p><p style='margin-left:-76%;margin-top:4%;'><div style='width:80%;'><b>(3:52 PM):</b><p style='word-break: break-all;'>data
</div></p></p></div><br><div class='msgln' style='background-color:#fff;height:auto;min-height:120px;color:#000;box-shadow: 5px 5px 3px #888888;overflow:auto;'> <img src='https://media.licdn.com/mpr/mprx/0_0eo-q-dnP-ouX37azJttx-_nK_zxGhlmrJtyAbmn-BoOGrGCzeYp0hfnvboxFP11PJ-prvh90qHYTX81KRfap63VsqH0TXQ7zRfAcFqclzjPw-g1MEMxBPV6VT-fHXAYyZwOKzHs74u' style='border-radius:25px;height:50px;width:50px;margin-top:1.5%;margin-left:-53%;'>&nbsp;&nbsp;&nbsp;<h5 style='color:#000;display:inline;margin-top:-5%;'>Aman Bharadwaj</h5>
            <p style='margin-top:-4%;margin-left:-45%;font-size:14px;color:#757575;'><b>Dehra Dun Area, India</b></p><p style='margin-left:-76%;margin-top:4%;'><div style='width:80%;'><b>(10:33 PM):</b><p style='word-break: break-all;'>Spain, a country on Europe’s Iberian Peninsula, includes 17 autonomous regions with diverse geography and cultures. Capital city Madrid is home to the Royal Palace and Prado museum, housing works by European masters. Segovia has a medieval castle (the Alcázar) and an intact Roman aqueduct. Catalonia’s capital, Barcelona, is defined by Antoni Gaudí’s whimsical modernist landmarks like the Sagrada Família church.</div></p></p></div><br><div class='msgln' style='background-color:#fff;height:auto;min-height:120px;color:#000;box-shadow: 5px 5px 3px #888888;overflow:auto;'> <img src='https://media.licdn.com/mpr/mprx/0_0eo-q-dnP-ouX37azJttx-_nK_zxGhlmrJtyAbmn-BoOGrGCzeYp0hfnvboxFP11PJ-prvh90qHYTX81KRfap63VsqH0TXQ7zRfAcFqclzjPw-g1MEMxBPV6VT-fHXAYyZwOKzHs74u' style='border-radius:25px;height:50px;width:50px;margin-top:1.5%;margin-left:-53%;'>&nbsp;&nbsp;&nbsp;<h5 style='color:#000;display:inline;margin-top:-5%;'>Aman Bharadwaj</h5>
            <p style='margin-top:-4%;margin-left:-45%;font-size:14px;color:#757575;'><b>Dehra Dun Area, India</b></p><p style='margin-left:-76%;margin-top:4%;'><div style='width:80%;'><b>(7:33 PM):</b><p style='word-break: break-all;'>PHP (recursive acronym for PHP: Hypertext Preprocessor) is a widely-used open source general-purpose scripting language that is especially suited for web development and can be embedded into HTML.</div></p></p></div><br><div class='msgln' style='background-color:#fff;height:auto;min-height:120px;color:#000;box-shadow: 5px 5px 3px #888888;overflow:auto;'> <img src='https://media.licdn.com/mpr/mprx/0_0eo-q-dnP-ouX37azJttx-_nK_zxGhlmrJtyAbmn-BoOGrGCzeYp0hfnvboxFP11PJ-prvh90qHYTX81KRfap63VsqH0TXQ7zRfAcFqclzjPw-g1MEMxBPV6VT-fHXAYyZwOKzHs74u' style='border-radius:25px;height:50px;width:50px;margin-top:1.5%;margin-left:-53%;'>&nbsp;&nbsp;&nbsp;<h5 style='color:#000;display:inline;margin-top:-5%;'>Aman Bharadwaj</h5>
            <p style='margin-top:-4%;margin-left:-45%;font-size:14px;color:#757575;'><b>Dehra Dun Area, India</b></p><p style='margin-left:-76%;margin-top:4%;'><div style='width:80%;'><b>(11:28 PM):</b><p style='word-break: break-all;'>hujhbhjb
</div></p></p></div>